apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-kart-deployment
  labels:
    app: neon-kart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neon-kart
  template:
    metadata:
      labels:
        app: neon-kart
    spec:
      containers:
      - name: neon-kart
        image: malikakash/neon-kart:latest
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        ports:
        - containerPort: 8000
